1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5
matrix. (Score:1)

In [1]:
import numpy as np

In [9]:
arr=np.array(range(1,11))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
arr=arr.reshape(2,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2. Create a numpy array containing the numbers from 1 to 20, and then extract the
elements between the 5th and 15th index.

In [12]:
crr=np.array(range(1,21))
print(crr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [30]:
print(crr[5:15])

[ 6  7  8  9 10 11 12 13 14 15]


3. How to compute the mean, median, and standard deviation of a numpy array?Use the
array you created above (Score 1)

In [16]:
mean=np.mean(crr)
median=np.median(crr)
std=np.std(crr)
print("Mean=",mean)
print("Median=",median)
print("Standard deviation=",std)

Mean= 10.5
Median= 10.5
Standard deviation= 5.766281297335398


4. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of
shape (4,). Subtract y from each row of x using broadcasting. (Score: 2)

In [19]:
x=np.array([[10,20,30,40],
            [50,60,70,80],
            [90,100,110,120]])
y=np.array([1,2,3,4])
print("2D: ",x)
print("1D: ",y)

2D:  [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
1D:  [1 2 3 4]


In [32]:
result=x-y
print(result)

[[  9  18  27  36]
 [ 49  58  67  76]
 [ 89  98 107 116]]


5. Create a dataframe with the following columns: name, age, and gender. The dataframe
should have 10 rows of data. (Score: 2)

In [22]:
import pandas as pd

In [23]:
data={ "name": ["John", "Alice", "Tom", "Emma", "David",
             "Sophia", "James", "Olivia", "Liam", "Mia"],
    "age": [25, 30, 22, 35, 28, 40, 32, 27, 45, 31],
    "gender": ["Male", "Female", "Male", "Female", "Male",
               "Female", "Male", "Female", "Male", "Female"]
       }
df=pd.DataFrame(data)
df

,name,age,gender
0,John,25,Male
1,Alice,30,Female
2,Tom,22,Male
3,Emma,35,Female
4,David,28,Male
5,Sophia,40,Female
6,James,32,Male
7,Olivia,27,Female
8,Liam,45,Male
9,Mia,31,Female


5.1) Add a new column to the data frame created in question 1, called occupation.
The values for this column should be Programmer, Manager, and Analyst,
corresponding to the rows in the dataframe. (Score: 1)

In [24]:
occupations=["Programmer","Manager","Analyst",
             "Programmer","Manager","Analyst",
             "Programmer","Manager","Analyst","Programmer"]
df["Occupation"]=occupations
df

,name,age,gender,Occupation
0,John,25,Male,Programmer
1,Alice,30,Female,Manager
2,Tom,22,Male,Analyst
3,Emma,35,Female,Programmer
4,David,28,Male,Manager
5,Sophia,40,Female,Analyst
6,James,32,Male,Programmer
7,Olivia,27,Female,Manager
8,Liam,45,Male,Analyst
9,Mia,31,Female,Programmer


5.2) Select the rows of the dataframe where the age is greater than or equal to 30.
(Score: 1)

In [27]:
res=df[df["age"]>=30]
res

,name,age,gender,Occupation
1,Alice,30,Female,Manager
3,Emma,35,Female,Programmer
5,Sophia,40,Female,Analyst
6,James,32,Male,Programmer
8,Liam,45,Male,Analyst
9,Mia,31,Female,Programmer


5.3) Convert this dataframe to a CSV file and read that CSV file, and finally display
the contents. (Score: 1)

In [28]:
df.to_csv("students.csv",index=False)

In [29]:
new_df=pd.read_csv("students.csv")
new_df

,name,age,gender,Occupation
0,John,25,Male,Programmer
1,Alice,30,Female,Manager
2,Tom,22,Male,Analyst
3,Emma,35,Female,Programmer
4,David,28,Male,Manager
5,Sophia,40,Female,Analyst
6,James,32,Male,Programmer
7,Olivia,27,Female,Manager
8,Liam,45,Male,Analyst
9,Mia,31,Female,Programmer
